CREATE TABLE IF NOT EXISTS datatypes (
    code INTEGER PRIMARY KEY,
    sensor_type TEXT NOT NULL,
    sensor_type_key TEXT NOT NULL,
    unit TEXT NOT NULL,
    unit_key TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS readings (
    rid INTEGER NOT NULL,
    dataid INTEGER NOT NULL,
    measured_at INTEGER NOT NULL,  -- DATETIME NOT NULL
    datatype INTEGER NOT NULL,
    PRIMARY KEY(rid),
    FOREIGN KEY(datatype) REFERENCES datatypes(code)
);

CREATE TABLE IF NOT EXISTS spectra_raw (
    id INTEGER NOT NULL,  -- AUTOINCREMENT
    row_inserted DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rid INTEGER NOT NULL,
    arr_idx INTEGER NOT NULL,
    measurement REAL NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(rid) REFERENCES readings(rid)
);

CREATE TABLE IF NOT EXISTS spectra_processed (
    id INTEGER NOT NULL,  -- AUTOINCREMENT
    row_inserted DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rid INTEGER NOT NULL,
    arr_idx INTEGER NOT NULL,
    measurement REAL NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(rid) REFERENCES readings(rid)
);

CREATE TABLE IF NOT EXISTS spectra_peaks (
    id INTEGER NOT NULL,  -- AUTOINCREMENT
    row_inserted DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rid INTEGER NOT NULL,
    center REAL NOT NULL,
    amplitude REAL NOT NULL,
    fwhm REAL NOT NULL,
    tag TEXT NOT NULL,
    tag_key TEXT NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(rid) REFERENCES spectra_processed(rid)
);


CREATE TABLE IF NOT EXISTS soil_humidity (
    id INTEGER NOT NULL,  -- AUTOINCREMENT
    row_inserted DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rid INTEGER NOT NULL,
    measurement REAL NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(rid) REFERENCES readings(rid)
);

CREATE TABLE IF NOT EXISTS soil_temperature (
    id INTEGER NOT NULL,  -- AUTOINCREMENT
    row_inserted DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rid INTEGER NOT NULL,
    measurement REAL NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(rid) REFERENCES readings(rid)
);

CREATE TABLE IF NOT EXISTS air_humidity (
    id INTEGER NOT NULL,  -- AUTOINCREMENT
    row_inserted DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rid INTEGER NOT NULL,
    measurement REAL NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(rid) REFERENCES readings(rid)
);

CREATE TABLE IF NOT EXISTS air_temperature (
    id INTEGER NOT NULL,  -- AUTOINCREMENT
    row_inserted DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rid INTEGER NOT NULL,
    measurement REAL NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(rid) REFERENCES readings(rid)
);

CREATE TABLE IF NOT EXISTS air_pressure (
    id INTEGER NOT NULL,  -- AUTOINCREMENT
    row_inserted DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rid INTEGER NOT NULL,
    measurement REAL NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(rid) REFERENCES readings(rid)
);

CREATE TABLE IF NOT EXISTS methane (
    id INTEGER NOT NULL,  -- AUTOINCREMENT
    row_inserted DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rid INTEGER NOT NULL,
    measurement REAL NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(rid) REFERENCES readings(rid)
);

CREATE TABLE IF NOT EXISTS ultraviolet (
    id INTEGER NOT NULL,  -- AUTOINCREMENT
    row_inserted DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rid INTEGER NOT NULL,
    measurement REAL NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(rid) REFERENCES readings(rid)
);

CREATE TABLE IF NOT EXISTS joint_angle (
    id INTEGER NOT NULL,  -- AUTOINCREMENT
    row_inserted DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rid INTEGER NOT NULL,
    measurement REAL NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(rid) REFERENCES readings(rid)
);

CREATE TABLE IF NOT EXISTS joint_speed (
    id INTEGER NOT NULL,  -- AUTOINCREMENT
    row_inserted DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rid INTEGER NOT NULL,
    measurement REAL NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(rid) REFERENCES readings(rid)
);

CREATE TABLE IF NOT EXISTS motors (
    id INTEGER NOT NULL,  -- AUTOINCREMENT
    row_inserted DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rid INTEGER NOT NULL,
    measurement REAL NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(rid) REFERENCES readings(rid)
);
