# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Sep  8 21:02:49 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(946, 542)
        MainWindow.setSizeIncrement(QtCore.QSize(1, 1))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.digsiteTabs = QtGui.QTabWidget(self.centralWidget)
        self.digsiteTabs.setObjectName(_fromUtf8("digsiteTabs"))
        self.currentSite = QtGui.QWidget()
        self.currentSite.setObjectName(_fromUtf8("currentSite"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.currentSite)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.inputFrame = QtGui.QHBoxLayout()
        self.inputFrame.setSpacing(7)
        self.inputFrame.setContentsMargins(20, -1, -1, -1)
        self.inputFrame.setObjectName(_fromUtf8("inputFrame"))
        self.realtimeButton = QtGui.QRadioButton(self.currentSite)
        self.realtimeButton.setObjectName(_fromUtf8("realtimeButton"))
        self.inputFrame.addWidget(self.realtimeButton)
        self.fileButton = QtGui.QRadioButton(self.currentSite)
        self.fileButton.setObjectName(_fromUtf8("fileButton"))
        self.inputFrame.addWidget(self.fileButton)
        self.fileInput = QtGui.QLineEdit(self.currentSite)
        self.fileInput.setMinimumSize(QtCore.QSize(400, 0))
        self.fileInput.setMaximumSize(QtCore.QSize(400, 16777215))
        self.fileInput.setObjectName(_fromUtf8("fileInput"))
        self.inputFrame.addWidget(self.fileInput)
        self.browseButton = QtGui.QPushButton(self.currentSite)
        self.browseButton.setObjectName(_fromUtf8("browseButton"))
        self.inputFrame.addWidget(self.browseButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.inputFrame.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.inputFrame)
        self.displayFrame = QtGui.QHBoxLayout()
        self.displayFrame.setSpacing(0)
        self.displayFrame.setObjectName(_fromUtf8("displayFrame"))
        self.sensorEnables = QtGui.QVBoxLayout()
        self.sensorEnables.setSpacing(0)
        self.sensorEnables.setContentsMargins(-1, 0, -1, -1)
        self.sensorEnables.setObjectName(_fromUtf8("sensorEnables"))
        self.tempSensors = QtGui.QGroupBox(self.currentSite)
        self.tempSensors.setMaximumSize(QtCore.QSize(100, 150))
        self.tempSensors.setObjectName(_fromUtf8("tempSensors"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tempSensors)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tsheath1 = QtGui.QCheckBox(self.tempSensors)
        self.tsheath1.setObjectName(_fromUtf8("tsheath1"))
        self.verticalLayout_4.addWidget(self.tsheath1)
        self.tsheath2 = QtGui.QCheckBox(self.tempSensors)
        self.tsheath2.setObjectName(_fromUtf8("tsheath2"))
        self.verticalLayout_4.addWidget(self.tsheath2)
        self.tdrill1 = QtGui.QCheckBox(self.tempSensors)
        self.tdrill1.setObjectName(_fromUtf8("tdrill1"))
        self.verticalLayout_4.addWidget(self.tdrill1)
        self.tdrill2 = QtGui.QCheckBox(self.tempSensors)
        self.tdrill2.setObjectName(_fromUtf8("tdrill2"))
        self.verticalLayout_4.addWidget(self.tdrill2)
        self.sensorEnables.addWidget(self.tempSensors)
        self.humidSensors = QtGui.QGroupBox(self.currentSite)
        self.humidSensors.setMaximumSize(QtCore.QSize(100, 150))
        self.humidSensors.setObjectName(_fromUtf8("humidSensors"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.humidSensors)
        self.verticalLayout_5.setSpacing(7)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.hsheath1 = QtGui.QCheckBox(self.humidSensors)
        self.hsheath1.setObjectName(_fromUtf8("hsheath1"))
        self.verticalLayout_5.addWidget(self.hsheath1)
        self.hsheath2 = QtGui.QCheckBox(self.humidSensors)
        self.hsheath2.setObjectName(_fromUtf8("hsheath2"))
        self.verticalLayout_5.addWidget(self.hsheath2)
        self.hdrill1 = QtGui.QCheckBox(self.humidSensors)
        self.hdrill1.setObjectName(_fromUtf8("hdrill1"))
        self.verticalLayout_5.addWidget(self.hdrill1)
        self.hdrill2 = QtGui.QCheckBox(self.humidSensors)
        self.hdrill2.setObjectName(_fromUtf8("hdrill2"))
        self.verticalLayout_5.addWidget(self.hdrill2)
        self.sensorEnables.addWidget(self.humidSensors)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.sensorEnables.addItem(spacerItem1)
        self.saveGraphsButton = QtGui.QPushButton(self.currentSite)
        self.saveGraphsButton.setObjectName(_fromUtf8("saveGraphsButton"))
        self.sensorEnables.addWidget(self.saveGraphsButton)
        self.displayFrame.addLayout(self.sensorEnables)
        self.graphTabs = QtGui.QTabWidget(self.currentSite)
        self.graphTabs.setObjectName(_fromUtf8("graphTabs"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tab_1)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.horizontalLayout_3.addWidget(self.plainTextEdit)
        self.graphTabs.addTab(self.tab_1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_2.setObjectName(_fromUtf8("plainTextEdit_2"))
        self.horizontalLayout_4.addWidget(self.plainTextEdit_2)
        self.graphTabs.addTab(self.tab_2, _fromUtf8(""))
        self.displayFrame.addWidget(self.graphTabs)
        self.verticalLayout_2.addLayout(self.displayFrame)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.digsiteTabs.addTab(self.currentSite, _fromUtf8(""))
        self.exSite = QtGui.QWidget()
        self.exSite.setObjectName(_fromUtf8("exSite"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.exSite)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.displayFrame_2 = QtGui.QHBoxLayout()
        self.displayFrame_2.setSpacing(0)
        self.displayFrame_2.setObjectName(_fromUtf8("displayFrame_2"))
        self.sensorEnables_2 = QtGui.QVBoxLayout()
        self.sensorEnables_2.setSpacing(0)
        self.sensorEnables_2.setObjectName(_fromUtf8("sensorEnables_2"))
        self.tempSensors_2 = QtGui.QGroupBox(self.exSite)
        self.tempSensors_2.setMaximumSize(QtCore.QSize(100, 150))
        self.tempSensors_2.setObjectName(_fromUtf8("tempSensors_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tempSensors_2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.tsheath1_2 = QtGui.QCheckBox(self.tempSensors_2)
        self.tsheath1_2.setObjectName(_fromUtf8("tsheath1_2"))
        self.verticalLayout_7.addWidget(self.tsheath1_2)
        self.tsheath2_2 = QtGui.QCheckBox(self.tempSensors_2)
        self.tsheath2_2.setObjectName(_fromUtf8("tsheath2_2"))
        self.verticalLayout_7.addWidget(self.tsheath2_2)
        self.tdrill1_2 = QtGui.QCheckBox(self.tempSensors_2)
        self.tdrill1_2.setObjectName(_fromUtf8("tdrill1_2"))
        self.verticalLayout_7.addWidget(self.tdrill1_2)
        self.tdrill2_2 = QtGui.QCheckBox(self.tempSensors_2)
        self.tdrill2_2.setObjectName(_fromUtf8("tdrill2_2"))
        self.verticalLayout_7.addWidget(self.tdrill2_2)
        self.sensorEnables_2.addWidget(self.tempSensors_2)
        self.humidSensors_2 = QtGui.QGroupBox(self.exSite)
        self.humidSensors_2.setMaximumSize(QtCore.QSize(100, 150))
        self.humidSensors_2.setObjectName(_fromUtf8("humidSensors_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.humidSensors_2)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.hsheath1_2 = QtGui.QCheckBox(self.humidSensors_2)
        self.hsheath1_2.setObjectName(_fromUtf8("hsheath1_2"))
        self.verticalLayout_8.addWidget(self.hsheath1_2)
        self.hsheath2_2 = QtGui.QCheckBox(self.humidSensors_2)
        self.hsheath2_2.setObjectName(_fromUtf8("hsheath2_2"))
        self.verticalLayout_8.addWidget(self.hsheath2_2)
        self.hdrill1_2 = QtGui.QCheckBox(self.humidSensors_2)
        self.hdrill1_2.setObjectName(_fromUtf8("hdrill1_2"))
        self.verticalLayout_8.addWidget(self.hdrill1_2)
        self.hdrill2_2 = QtGui.QCheckBox(self.humidSensors_2)
        self.hdrill2_2.setObjectName(_fromUtf8("hdrill2_2"))
        self.verticalLayout_8.addWidget(self.hdrill2_2)
        self.sensorEnables_2.addWidget(self.humidSensors_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.sensorEnables_2.addItem(spacerItem2)
        self.displayFrame_2.addLayout(self.sensorEnables_2)
        self.graphTabs_2 = QtGui.QTabWidget(self.exSite)
        self.graphTabs_2.setObjectName(_fromUtf8("graphTabs_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.plainTextEdit_3 = QtGui.QPlainTextEdit(self.tab_3)
        self.plainTextEdit_3.setObjectName(_fromUtf8("plainTextEdit_3"))
        self.horizontalLayout_7.addWidget(self.plainTextEdit_3)
        self.graphTabs_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.plainTextEdit_4 = QtGui.QPlainTextEdit(self.tab_4)
        self.plainTextEdit_4.setObjectName(_fromUtf8("plainTextEdit_4"))
        self.horizontalLayout_8.addWidget(self.plainTextEdit_4)
        self.graphTabs_2.addTab(self.tab_4, _fromUtf8(""))
        self.displayFrame_2.addWidget(self.graphTabs_2)
        self.verticalLayout_9.addLayout(self.displayFrame_2)
        self.digsiteTabs.addTab(self.exSite, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.digsiteTabs)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.digsiteTabs.setCurrentIndex(1)
        self.graphTabs.setCurrentIndex(1)
        self.graphTabs_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.realtimeButton.setText(_translate("MainWindow", "Realtime", None))
        self.fileButton.setText(_translate("MainWindow", "File", None))
        self.browseButton.setText(_translate("MainWindow", "Browse", None))
        self.tempSensors.setTitle(_translate("MainWindow", "Temperature", None))
        self.tsheath1.setText(_translate("MainWindow", "Sheath1", None))
        self.tsheath2.setText(_translate("MainWindow", "Sheath2", None))
        self.tdrill1.setText(_translate("MainWindow", "Drill1", None))
        self.tdrill2.setText(_translate("MainWindow", "Drill2", None))
        self.humidSensors.setTitle(_translate("MainWindow", "Humidity", None))
        self.hsheath1.setText(_translate("MainWindow", "Sheath1", None))
        self.hsheath2.setText(_translate("MainWindow", "Sheath2", None))
        self.hdrill1.setText(_translate("MainWindow", "Drill1", None))
        self.hdrill2.setText(_translate("MainWindow", "Drill2", None))
        self.saveGraphsButton.setText(_translate("MainWindow", "Save Graphs", None))
        self.graphTabs.setTabText(self.graphTabs.indexOf(self.tab_1), _translate("MainWindow", "Tab 1", None))
        self.graphTabs.setTabText(self.graphTabs.indexOf(self.tab_2), _translate("MainWindow", "Tab 2", None))
        self.digsiteTabs.setTabText(self.digsiteTabs.indexOf(self.currentSite), _translate("MainWindow", "Tab 1", None))
        self.tempSensors_2.setTitle(_translate("MainWindow", "Temperature", None))
        self.tsheath1_2.setText(_translate("MainWindow", "Sheath1", None))
        self.tsheath2_2.setText(_translate("MainWindow", "Sheath2", None))
        self.tdrill1_2.setText(_translate("MainWindow", "Drill1", None))
        self.tdrill2_2.setText(_translate("MainWindow", "Drill2", None))
        self.humidSensors_2.setTitle(_translate("MainWindow", "Humidity", None))
        self.hsheath1_2.setText(_translate("MainWindow", "Sheath1", None))
        self.hsheath2_2.setText(_translate("MainWindow", "Sheath2", None))
        self.hdrill1_2.setText(_translate("MainWindow", "Drill1", None))
        self.hdrill2_2.setText(_translate("MainWindow", "Drill2", None))
        self.graphTabs_2.setTabText(self.graphTabs_2.indexOf(self.tab_3), _translate("MainWindow", "Tab 1", None))
        self.graphTabs_2.setTabText(self.graphTabs_2.indexOf(self.tab_4), _translate("MainWindow", "Tab 2", None))
        self.digsiteTabs.setTabText(self.digsiteTabs.indexOf(self.exSite), _translate("MainWindow", "Tab 2", None))

